#!/usr/bin/env python3
"""Rebuild docs/tables/shortlist_coverage.csv (+ TeX) from shortlist meta.json files.

Reads recall_L_* from:
  outputs/sid_e2e_shortlist/{amazon,yelp,goodreads}/m{100,200,500}/meta.json

Falls back to the legacy Amazon flat layout outputs/sid_e2e_shortlist/m{M}/.

Example:
  python scripts/refresh_shortlist_coverage_table.py
  python scripts/refresh_shortlist_coverage_table.py --require_text_baselines
"""
from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = ROOT / "outputs" / "sid_e2e_shortlist"
CSV_PATH = ROOT / "docs" / "tables" / "shortlist_coverage.csv"
TEX_PATH = ROOT / "docs" / "tables" / "shortlist_coverage.tex"

DATASETS = ("amazon", "yelp", "goodreads")
DOMAIN_LABEL = {"amazon": "Amazon", "yelp": "Yelp", "goodreads": "Goodreads"}
# Domain display order.
DISPLAY_ORDER = ("Amazon", "Goodreads", "Yelp")
MS = (100, 200, 500)

FIELDS = [
    "domain",
    "M",
    "n",
    "rand",
    "bm25",
    "embnn",
    "sid",
    "sasrec",
    "sid_minus_rand",
    "sid_minus_bm25",
    "sid_minus_embnn",
    "sasrec_minus_rand",
]


def resolve_meta(output_root: Path, dataset: str, m: int) -> Path | None:
    nested = output_root / dataset / f"m{m}" / "meta.json"
    if nested.is_file():
        return nested
    if dataset == "amazon":
        flat = output_root / f"m{m}" / "meta.json"
        if flat.is_file():
            return flat
    return None


def fmt3(x: float | None) -> str:
    if x is None:
        return ""
    return f"{x:.3f}"


def fmt_delta(x: float | None) -> str:
    if x is None:
        return ""
    return f"{x:+.3f}"


def load_cell(output_root: Path, dataset: str, m: int) -> dict | None:
    path = resolve_meta(output_root, dataset, m)
    if path is None:
        return None
    meta = json.loads(path.read_text())
    rand = meta.get("recall_L_random")
    sid = meta.get("recall_L_sid")
    sas = meta.get("recall_L_sasrec")
    bm25 = meta.get("recall_L_bm25")
    embnn = meta.get("recall_L_embnn")
    n = meta.get("n_tasks")
    if n is None:
        uni = path.parent / "universes.jsonl"
        n = sum(1 for _ in uni.open()) if uni.is_file() else None

    def _f(v):
        return float(v) if v is not None else None

    rand_f, sid_f, sas_f = _f(rand), _f(sid), _f(sas)
    bm25_f, embnn_f = _f(bm25), _f(embnn)
    return {
        "domain": DOMAIN_LABEL[dataset],
        "M": m,
        "n": int(n) if n is not None else "",
        "rand": rand_f,
        "bm25": bm25_f,
        "embnn": embnn_f,
        "sid": sid_f,
        "sasrec": sas_f,
        "sid_minus_rand": (sid_f - rand_f) if sid_f is not None and rand_f is not None else None,
        "sid_minus_bm25": (sid_f - bm25_f) if sid_f is not None and bm25_f is not None else None,
        "sid_minus_embnn": (sid_f - embnn_f) if sid_f is not None and embnn_f is not None else None,
        "sasrec_minus_rand": (sas_f - rand_f) if sas_f is not None and rand_f is not None else None,
        "_path": str(path),
    }


def write_csv(rows: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=FIELDS, extrasaction="ignore")
        w.writeheader()
        for r in rows:
            out = {
                "domain": r["domain"],
                "M": r["M"],
                "n": r["n"],
                "rand": fmt3(r["rand"]),
                "bm25": fmt3(r["bm25"]),
                "embnn": fmt3(r["embnn"]),
                "sid": fmt3(r["sid"]),
                "sasrec": fmt3(r["sasrec"]),
                "sid_minus_rand": fmt_delta(r["sid_minus_rand"]),
                "sid_minus_bm25": fmt_delta(r["sid_minus_bm25"]),
                "sid_minus_embnn": fmt_delta(r["sid_minus_embnn"]),
                "sasrec_minus_rand": fmt_delta(r["sasrec_minus_rand"]),
            }
            w.writerow(out)


def _bold_best(values: dict[str, float | None], keys: list[str]) -> dict[str, bool]:
    present = {k: values[k] for k in keys if values.get(k) is not None}
    if not present:
        return {k: False for k in keys}
    best = max(present.values())
    # Prefer SID on ties.
    winner = "sid" if present.get("sid") == best else max(present, key=present.get)
    return {k: (k == winner) for k in keys}


def write_tex(rows: list[dict], path: Path) -> None:
    lines = [
        "% Auto-generated by scripts/refresh_shortlist_coverage_table.py",
        "% Source CSV: docs/tables/shortlist_coverage.csv",
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\caption{Candidate-pool shortlisting Recall@$20$ on identical candidate",
        r"universes. Training-free text baselines (BM25, content-embedding NN) use",
        r"the same $U_t$ as random / SID / SASRec. $\Delta_{\mathrm{SID-Rand}}$ is",
        r"the absolute Recall@$20$ lift of SID over random. Bold marks the best",
        r"method among SID, BM25, EmbNN, and SASRec when it also beats random.}",
        r"\label{tab:shortlist-coverage}",
        r"\begin{tabular}{llrrrrrrr}",
        r"\toprule",
        r"\textbf{Domain} & \textbf{$M$} & \textbf{$n$} &",
        r"\textbf{Rand} & \textbf{BM25} & \textbf{EmbNN} &",
        r"\textbf{SID} & \textbf{SASRec} & \textbf{SID--Rand} \\",
        r"\midrule",
    ]

    by_domain: dict[str, list[dict]] = {d: [] for d in DISPLAY_ORDER}
    for r in rows:
        by_domain.setdefault(r["domain"], []).append(r)

    first_domain = True
    for domain in DISPLAY_ORDER:
        cells = sorted(by_domain.get(domain, []), key=lambda r: int(r["M"]))
        if not cells:
            continue
        if not first_domain:
            lines.append(r"\midrule")
        first_domain = False
        for r in cells:
            marks = _bold_best(r, ["sid", "bm25", "embnn", "sasrec"])
            # Only bold if also beats random.
            for k in list(marks):
                if marks[k] and r.get("rand") is not None and r.get(k) is not None:
                    if r[k] <= r["rand"]:
                        marks[k] = False

            def cell(key: str) -> str:
                v = r.get(key)
                if v is None:
                    return "---"
                s = f"{v:.3f}"
                return rf"$\mathbf{{{s}}}$" if marks.get(key) else s

            delta = r.get("sid_minus_rand")
            delta_s = f"${delta:+.3f}$" if delta is not None else "---"
            lines.append(
                f"{domain} & ${int(r['M'])}$ & ${r['n']}$ & "
                f"{fmt3(r['rand'])} & {cell('bm25')} & {cell('embnn')} & "
                f"{cell('sid')} & {cell('sasrec')} & {delta_s} \\\\"
            )

    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        "",
    ]
    path.write_text("\n".join(lines))


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--output_root", type=Path, default=DEFAULT_OUT)
    p.add_argument("--csv_path", type=Path, default=CSV_PATH)
    p.add_argument("--tex_path", type=Path, default=TEX_PATH)
    p.add_argument(
        "--require_text_baselines",
        action="store_true",
        help="Fail if any cell is missing recall_L_bm25 or recall_L_embnn",
    )
    p.add_argument(
        "--keep_missing",
        action="store_true",
        help="Keep cells even if rand/sid missing (default: skip incomplete cells)",
    )
    return p.parse_args()


def main() -> None:
    args = parse_args()
    rows = []
    missing = []
    for dataset in DATASETS:
        for m in MS:
            cell = load_cell(args.output_root, dataset, m)
            if cell is None:
                missing.append(f"{dataset}/m{m}")
                continue
            if not args.keep_missing and (cell["rand"] is None or cell["sid"] is None):
                missing.append(f"{dataset}/m{m} (incomplete rand/sid)")
                continue
            if args.require_text_baselines and (
                cell["bm25"] is None or cell["embnn"] is None
            ):
                raise SystemExit(
                    f"Missing BM25/EmbNN recalls in {cell['_path']}. "
                    f"Run scripts/add_text_shortlist_arms.py first."
                )
            rows.append(cell)

    if not rows:
        raise SystemExit(
            f"No meta.json found under {args.output_root}. "
            f"Missing: {', '.join(missing) or 'all'}"
        )

    # Stable domain order
    rank = {d: i for i, d in enumerate(DISPLAY_ORDER)}
    rows.sort(key=lambda r: (rank.get(r["domain"], 99), int(r["M"])))

    write_csv(rows, args.csv_path)
    write_tex(rows, args.tex_path)
    print(f"wrote {args.csv_path} ({len(rows)} rows)")
    print(f"wrote {args.tex_path}")
    if missing:
        print("note: skipped " + "; ".join(missing), file=sys.stderr)

    # Compact console table
    hdr = f"{'Domain':10} {'M':>4} {'n':>4} {'Rand':>6} {'BM25':>6} {'EmbNN':>6} {'SID':>6} {'SAS':>6}"
    print(hdr)
    for r in rows:
        print(
            f"{r['domain']:10} {int(r['M']):4d} {str(r['n']):>4} "
            f"{fmt3(r['rand']):>6} {fmt3(r['bm25']):>6} {fmt3(r['embnn']):>6} "
            f"{fmt3(r['sid']):>6} {fmt3(r['sasrec']):>6}"
        )


if __name__ == "__main__":
    main()
